### ISSUE TITLE
ignore line returns when reading pdf

### ISSUE THREAD

**Issue by Zedroid** [lesleyrs/clipboard-narrator#1]
I love how you automatically intercept or interrupt my keybaord with my program after copying wihtout any need to press a hotkey like in https://github.com/Daichi09/ClipboardTTS
but one feautre I might want you to port over is to ignore and line returns.  This comes in handy for pdf files.  

;Remove unwanted pause from Line Returns
RemoveLineReturns = "true"
from ahk.exe .settings file

Thank you for the GUI good for casual users make it easier to know which voices they can switch to

**Comment by lesleyrs** [comment]
Agreed, fixed in https://github.com/lesleyrs/clipboard-narrator/commit/5ba2c55d4ae1dc8262d62b542bbb0922e453e42b and created new release.

I had to remove all newlines between paragraphs (which I consider double newlines) to guarantee it to work, periods by themselves pause speech for a moment anyway.

There's another problem with PDFs where you can't copy any newlines between paragraphs at all due to how they work. This is not a problem here but I created another tts app that splits at paragraphs to allow going back and forth https://github.com/lesleyrs/tts-tui. It has less features but if you care about that feature you can check it out and convert PDF files to TXT files with original layout (convertio.co works) otherwise that's it. 👍
